---
abstract: 'Install Devel::Cover and its recommended dependencies.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::Differences: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Devel-Cover-Recommended
no_index:
  directory:
    - t
    - inc
requires:
  Browser::Open: 0
  Devel::Cover: 0.93
  Digest::MD5: 0
  JSON::PP: 0
  PPI::HTML: 1.07
  Parallel::Iterator: 0
  Pod::Coverage: 0.06
  Pod::Coverage::CountParents: 0
  Storable: 0
  Template: 2.00
  perl: 5.008002
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Task-Devel-Cover-Recommended
  homepage: http://search.cpan.org/dist/Task-Devel-Cover-Recommended/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2FTask-Devel-Cover-Recommended.git
version: v0.93.0
